name: .NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore Enigma.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore Enigma.sln

    - name: Test
      run: dotnet test --no-restore --verbosity normal Enigma.sln
